name: Feature request
description: When you want to propose a new feature
title: "[Feature]: TheNameOfYourFeature"
labels: []
assignees: []

body:
  - type: textarea
    attributes:
      label: Describe the problem
      description: "E.g. I can't easily navigate to the home page"
      value: ""
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your solution
      description: "E.g. Add a home button"
      value: ""
    validations:
      required: true
  - type: textarea
    attributes:
      label: "[OPTIONAL] Describe alternatives"
      description: "E.g. Improve the other all navigation system"
      value: ""
  - type: textarea
    attributes:
      label: "[OPTIONAL] Additional context"
      description: "E.g. Pictures, screenshots, and other context information to help us understand the feature you would like"
      value: ""
