name: Feature request
description: When you want to propose a new feature
title: "[Feature]: "
labels: []
assignees: []

body:
  - type: textarea
    attributes:
      label: Describe the problem
      value: |
        E.g. I can't easily navigate to the home page
  - type: textarea
    attributes:
      value: |
        **Describe your solution**
        E.g. Add a home button
  - type: textarea
    attributes:
      value: |
        **[OPTIONAL] Describe alternatives**
        E.g. Improve the other all navigation system
  - type: textarea
    attributes:
      value: |
        **[OPTIONAL] Additional context**
        E.g. Pictures, screenshots, and other context information to help us understand the feature you would like
