name: Feature request
description: When you want to propose a new feature
title: "[Feature]: "
labels: []
assignees: []

body:
  - type: textarea
    attributes:
      label: Describe the problem
      value: |
        E.g. I can't easily navigate to the home page
      validations:
        required: true
  - type: textarea
    attributes:
      label: Describe your solution
      value: |
        E.g. Add a home button
      validations:
        required: true
  - type: textarea
    attributes:
      label: "[OPTIONAL] Describe alternatives"
      value: |
        E.g. Improve the other all navigation system
  - type: textarea
    attributes:
      label: "[OPTIONAL] Additional context"
      value: |
        E.g. Pictures, screenshots, and other context information to help us understand the feature you would like
